name: Publish @surplus/s
on:
  push:
    tags:
      - 's/*'

jobs:
  wait-for-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: ready-for-publish
          ref: ${{ github.sha }}
  publish:
    needs: wait-for-ci
    runs-on: ubuntu-latest
    if: needs.wait-for-ci.outputs.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - uses: './.github/actions/publish-npm'
        with:
          working-directory: 's'
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          package-name: '@surplus/s'
