name: Publish @surplus/rt
on:
  push:
    tags:
      - 'rt/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: ready-for-publish
          ref: ${{ github.sha }}
      - run: exit 1
        if: steps.wait-for-build.outputs.conclusion != 'success'
      - uses: actions/checkout@v4
      - uses: './.github/actions/publish-npm'
        with:
          working-directory: 'rt'
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          package-name: '@surplus/rt'
