name: Lint & Test
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run prepare-ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - run: npm run bench
  ready-for-publish:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - run: ':'
