name: Publish to Crates.io
description: Publishes a Surplus package to Crates.io
inputs:
  package:
    description: 'The package name (also the working directory, which must match surplus-<name>)'
    required: true
  cratesio-token:
    description: 'The Crates.io token to use for publishing'
    required: true
  ref:
    description: '${GITHUB_REF}'
    required: true
runs:
  using: composite
  steps:
    - run: sudo apt install -y jq
      shell: bash
    - run: |
        echo GITHUB_REF=${GITHUB_REF}
        echo VERSION=${GITHUB_REF#refs/tags/${{ inputs.package }}/}
      shell: bash
      env:
        GITHUB_REF: ${{ inputs.ref }}
    - name: Ensure that tag is a valid semver version string
      run: |
        if ! npx -y semver "${GITHUB_REF#refs/tags/${{ inputs.package }}/}" ; then
          echo "Tag is not a valid semver version string"
          exit 1
        fi
      env:
        GITHUB_REF: ${{ inputs.ref }}
      shell: bash
    - name: Check that specified package name matches Cargo.toml name
      run: |
        if ! cargo metadata --format-version=1 --offline --frozen --no-deps | jq -e '.packages[] | select(.name == "surplus-${{ inputs.package }}")' >/dev/null ; then
          echo "Specified package name does not match Cargo.toml name"
          exit 1
        fi
      shell: bash
      working-directory: ${{ inputs.package }}
    - name: Check Cargo.toml version against tag
      run: |
        CARGO_TOML_VERSION="$(cargo metadata --format-version=1 --offline --frozen --no-deps | jq -re '.packages[] | select(.name == "surplus-${{ inputs.package }}") | .version'"
        if [ "${CARGO_TOML_VERSION}" != "${GITHUB_REF#refs/tags/${{ inputs.package }}/}" ]; then
          echo "Tag version does not match Cargo.toml version"
          exit 1
        fi
      shell: bash
      working-directory: ${{ inputs.package }}
      env:
        GITHUB_REF: ${{ inputs.ref }}
    - name: Make sure tag is newer than latest version published on npm
      run: |
        if ! npx -y semver --range ">$(cargo search 'surplus-${{ inputs.package }}' --limit 1 | awk '{print $3}' | tr -d '()' | jq -r .)" "${GITHUB_REF#refs/tags/${{ inputs.package }}/}" ; then
          echo "Tag version is not newer than latest version published on Crates.io; manual publish required"
          exit 1
        fi
      shell: bash
      working-directory: ${{ inputs.package }}
      env:
        GITHUB_REF: ${{ inputs.ref }}
    - run: npm i
      shell: bash
    - run: npm run build
      if: inputs.build == 'true'
      working-directory: ${{ inputs.package }}
      shell: bash
    - run: cargo publish
      working-directory: ${{ inputs.package }}
      env:
        CARGO_REGISTRY_TOKEN: ${{ inputs.cratesio-token }}
      shell: bash

